[theme]
theme = "modern"

[[block]]
block = "cpu"
interval = 5
format = " CPU: $utilization "

[[block]]
block = "memory"
format = " RAM: $mem_used/$mem_total "
interval = 5

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S ')"

[[block]]
block = "custom"
command = "dunstctl count waiting"
interval = 1
signal = 12

[[block.click]]
button = "left"
cmd = "dunstctl history-pop"